// src/components/PostCard.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { MapPin, Eye, Calendar } from 'lucide-react';
import { Post } from '../types';
import { formatDate, truncateText } from '../lib/utils';

interface PostCardProps {
  post: Post;
}

const PostCard: React.FC<PostCardProps> = ({ post }) => {
  return (
    <div className="bg-white rounded-2xl shadow-sm hover:shadow-xl transition-all duration-300 overflow-hidden group border border-gray-100">
      <div className="relative h-64 overflow-hidden">
        <img
          src={post.thumbnail || `https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg?auto=compress&cs=tinysrgb&w=800`}
          alt={post.title}
          className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent" />
        {post.location && (
          <div className="absolute bottom-3 left-3 flex items-center space-x-1 text-white text-sm">
            <MapPin className="h-4 w-4" />
            <span className="font-medium">{post.location}</span>
          </div>
        )}
      </div>

      <div className="p-6">
        <div className="flex items-center space-x-4 text-sm text-gray-500 mb-3">
          <div className="flex items-center space-x-1">
            <Calendar className="h-4 w-4" />
            <span>{formatDate(post.createdAt)}</span>
          </div>
          <div className="flex items-center space-x-1">
            <Eye className="h-4 w-4" />
            <span>{post.views} views</span>
          </div>
        </div>

        <h2 className="text-xl font-bold text-gray-900 mb-3 line-clamp-2 group-hover:text-blue-600 transition-colors">
          {post.title}
        </h2>

        <p className="text-gray-600 text-sm leading-relaxed mb-4 line-clamp-3">
          {truncateText(post.excerpt || post.content, 120)}
        </p>

        <Link
          to={`/post/${post.slug}-${post.hash}`}
          className="inline-flex items-center text-blue-600 font-medium hover:text-blue-700 transition-colors"
        >
          Read more
          <span className="ml-1 group-hover:translate-x-1 transition-transform duration-200">→</span>
        </Link>
      </div>
    </div>
  );
};

export default PostCard;

// src/components/user/PostCard.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import { useRouter } from 'vue-router'
import { formatDate } from '../../utils/formatters'
import type { Post } from '../../stores/posts'

const props = defineProps<{
  post: Post
}>()

const router = useRouter()

function goToPost(id: string) {
  router.push(`/post/${id}`)
}
</script>

<template>
  <div 
    class="card group cursor-pointer h-full flex flex-col"
    @click="goToPost(post.id)"
  >
    <div class="aspect-w-16 aspect-h-9 overflow-hidden">
      <img 
        :src="post.coverImage" 
        :alt="post.title" 
        class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
      />
    </div>
    <div class="p-6 flex flex-col flex-grow">
      <div class="flex items-center justify-between text-sm text-gray-500 mb-2">
        <span>{{ formatDate(post.date) }}</span>
        <span class="bg-primary-100 text-primary-800 px-2 py-1 rounded-full text-xs">
          {{ post.category }}
        </span>
      </div>
      <h3 class="text-xl font-bold text-gray-900 mb-2 group-hover:text-primary-600 transition-colors">
        {{ post.title }}
      </h3>
      <p class="text-gray-600 mb-4 flex-grow">{{ post.excerpt }}</p>
      
      <div class="flex flex-wrap gap-2 mb-4">
        <span 
          v-for="tag in post.tags" 
          :key="tag" 
          class="bg-gray-100 text-gray-600 px-2 py-1 rounded-full text-xs"
        >
          #{{ tag }}
        </span>
      </div>
      
      <div class="flex items-center justify-between mt-auto">
        <div class="flex items-center">
          <img 
            :src="post.author.avatar" 
            :alt="post.author.name" 
            class="h-8 w-8 rounded-full mr-2"
          />
          <span class="text-sm text-gray-700">{{ post.author.name }}</span>
        </div>
        <div class="text-sm text-gray-500 flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
          </svg>
          {{ post.views }}
        </div>
      </div>
    </div>
  </div>
</template>
